services:
  dashboard:
    build: .
    container_name: dashboard
    ports:
      - "4001:4001" # backend API
      # - "3001:3000" # frontend dev server
    environment:
      - DEV_MODE=false
      - ALLOWED_ORIGINS=http://localhost:4001
      - IDP_URL=http://127.0.0.1:4002
      - AUTH_ENABLED=false
    volumes:
      - ./backend:/app/backend # optional: live code updates
      - ./frontend:/app/frontend # optional: live frontend updates
      - ./processes.json:/app/processes.json # optional: live PM2 config updates
      - /app/backend/node_modules
    # command: pm2-runtime /app/processes.json