GET http://localhost:2001/links
###

POST http://localhost:2001/link
Content-Type : application/json

{
    "name":"sabNZBD",
    "localIp":"127.0.0.1:7878",
    "remoteIp":"https://sab.example.com/",
    "imgUrl":"https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/plex.png",
    "column":"2"

}
###

DELETE http://localhost:2001/link/44
###


PATCH http://localhost:2001/links/move
Content-Type : application/json

{
    "idToMove":"68",
    "relativeToId":"",
    "position":"before",
    "targetColumn": "3"
}
###




PATCH http://localhost:2001/link/22
Content-Type : application/json

{
    "imgurl":"https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sabnzbd.png"
}
###

GET http://localhost:3000/links
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2lhbjEiLCJpYXQiOjE3NTY4MTY3NjEsImV4cCI6MTc1NzAxNjc2MX0.ihSn_F7MBE9ZQZG2Uof4TLqx382fzgFWYe-DINq7uuI
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9iIiwiaWF0IjoxNzU2Mjk3MjM2fQ.9eyLQxnp7tJHG30rMkzbZFpYMl8LM8T8kHoKEhl9Kqk"
}
###

POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "kian5",
    "password": "1234"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2lhbjEiLCJpYXQiOjE3NTY4MTU3MzJ9.eHjKzKZxnoBGwGMoalvSmIMJU5cdXXqGsrAygkLHvhQ"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"kian1",
    "password": "1234"
}